// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyLocalModel(arg1) {
  return window['go']['main']['App']['ApplyLocalModel'](arg1);
}

export function ApproveWebSearch(arg1) {
  return window['go']['main']['App']['ApproveWebSearch'](arg1);
}

export function BrowseIndex(arg1) {
  return window['go']['main']['App']['BrowseIndex'](arg1);
}

export function CancelBatchWorkflow() {
  return window['go']['main']['App']['CancelBatchWorkflow']();
}

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function ClearBatchPresetSelection() {
  return window['go']['main']['App']['ClearBatchPresetSelection']();
}

export function ClearBatchWorkflowState() {
  return window['go']['main']['App']['ClearBatchWorkflowState']();
}

export function ClearExecutionHistory() {
  return window['go']['main']['App']['ClearExecutionHistory']();
}

export function DeleteLocalConfigFile(arg1) {
  return window['go']['main']['App']['DeleteLocalConfigFile'](arg1);
}

export function DeleteProjectPreset(arg1) {
  return window['go']['main']['App']['DeleteProjectPreset'](arg1);
}

export function DeleteSavedRequest(arg1) {
  return window['go']['main']['App']['DeleteSavedRequest'](arg1);
}

export function Embeddings(arg1) {
  return window['go']['main']['App']['Embeddings'](arg1);
}

export function Eval(arg1) {
  return window['go']['main']['App']['Eval'](arg1);
}

export function ExportResult(arg1) {
  return window['go']['main']['App']['ExportResult'](arg1);
}

export function GetBatchPresetSelection() {
  return window['go']['main']['App']['GetBatchPresetSelection']();
}

export function GetBatchWorkflowState() {
  return window['go']['main']['App']['GetBatchWorkflowState']();
}

export function GetExecutionHistory() {
  return window['go']['main']['App']['GetExecutionHistory']();
}

export function GetGatewayURL() {
  return window['go']['main']['App']['GetGatewayURL']();
}

export function GetIndexSource(arg1) {
  return window['go']['main']['App']['GetIndexSource'](arg1);
}

export function GetLocalConfigFiles() {
  return window['go']['main']['App']['GetLocalConfigFiles']();
}

export function GetLocalModelCatalog() {
  return window['go']['main']['App']['GetLocalModelCatalog']();
}

export function GetProjectPresets() {
  return window['go']['main']['App']['GetProjectPresets']();
}

export function GetRegressionWatchProfiles() {
  return window['go']['main']['App']['GetRegressionWatchProfiles']();
}

export function GetRegressionWatchSettings() {
  return window['go']['main']['App']['GetRegressionWatchSettings']();
}

export function GetRuntimeStatus() {
  return window['go']['main']['App']['GetRuntimeStatus']();
}

export function GetSavedRequests() {
  return window['go']['main']['App']['GetSavedRequests']();
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ImportLocalModel(arg1) {
  return window['go']['main']['App']['ImportLocalModel'](arg1);
}

export function Ingest(arg1) {
  return window['go']['main']['App']['Ingest'](arg1);
}

export function ListExportedResults() {
  return window['go']['main']['App']['ListExportedResults']();
}

export function LoadLocalConfigExample(arg1) {
  return window['go']['main']['App']['LoadLocalConfigExample'](arg1);
}

export function Models() {
  return window['go']['main']['App']['Models']();
}

export function OpenWebSource(arg1) {
  return window['go']['main']['App']['OpenWebSource'](arg1);
}

export function PlanWebSearch(arg1) {
  return window['go']['main']['App']['PlanWebSearch'](arg1);
}

export function Query(arg1) {
  return window['go']['main']['App']['Query'](arg1);
}

export function ReadExportedResult(arg1) {
  return window['go']['main']['App']['ReadExportedResult'](arg1);
}

export function RecordExecution(arg1) {
  return window['go']['main']['App']['RecordExecution'](arg1);
}

export function ReloadGatewayConfig() {
  return window['go']['main']['App']['ReloadGatewayConfig']();
}

export function RoutePlan(arg1) {
  return window['go']['main']['App']['RoutePlan'](arg1);
}

export function RunChatAction(arg1) {
  return window['go']['main']['App']['RunChatAction'](arg1);
}

export function RunEmbeddingAction(arg1) {
  return window['go']['main']['App']['RunEmbeddingAction'](arg1);
}

export function RunEvalAction(arg1) {
  return window['go']['main']['App']['RunEvalAction'](arg1);
}

export function RunIndexBrowseAction(arg1) {
  return window['go']['main']['App']['RunIndexBrowseAction'](arg1);
}

export function RunIngestAction(arg1) {
  return window['go']['main']['App']['RunIngestAction'](arg1);
}

export function RunPresetEval(arg1) {
  return window['go']['main']['App']['RunPresetEval'](arg1);
}

export function RunPresetIngest(arg1) {
  return window['go']['main']['App']['RunPresetIngest'](arg1);
}

export function RunPresetIngestEval(arg1) {
  return window['go']['main']['App']['RunPresetIngestEval'](arg1);
}

export function RunPresetRecoveryAction(arg1) {
  return window['go']['main']['App']['RunPresetRecoveryAction'](arg1);
}

export function RunPresetRuntimeStackPrepare(arg1) {
  return window['go']['main']['App']['RunPresetRuntimeStackPrepare'](arg1);
}

export function RunPresetSmoke(arg1) {
  return window['go']['main']['App']['RunPresetSmoke'](arg1);
}

export function RunPresetStackIngestEval(arg1) {
  return window['go']['main']['App']['RunPresetStackIngestEval'](arg1);
}

export function RunPresetValidate(arg1) {
  return window['go']['main']['App']['RunPresetValidate'](arg1);
}

export function RunPresetVerification(arg1) {
  return window['go']['main']['App']['RunPresetVerification'](arg1);
}

export function RunPresetWatch(arg1) {
  return window['go']['main']['App']['RunPresetWatch'](arg1);
}

export function RunRagQueryAction(arg1) {
  return window['go']['main']['App']['RunRagQueryAction'](arg1);
}

export function RunRagSearchAction(arg1) {
  return window['go']['main']['App']['RunRagSearchAction'](arg1);
}

export function RunRuntimeConfigAction(arg1) {
  return window['go']['main']['App']['RunRuntimeConfigAction'](arg1);
}

export function RunRuntimeServiceAction(arg1) {
  return window['go']['main']['App']['RunRuntimeServiceAction'](arg1);
}

export function RunRuntimeSmoke(arg1) {
  return window['go']['main']['App']['RunRuntimeSmoke'](arg1);
}

export function RunRuntimeStackAction(arg1) {
  return window['go']['main']['App']['RunRuntimeStackAction'](arg1);
}

export function SaveLocalConfigFile(arg1) {
  return window['go']['main']['App']['SaveLocalConfigFile'](arg1);
}

export function SaveProjectPreset(arg1) {
  return window['go']['main']['App']['SaveProjectPreset'](arg1);
}

export function SaveRequest(arg1) {
  return window['go']['main']['App']['SaveRequest'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SetBatchPresetSelection(arg1) {
  return window['go']['main']['App']['SetBatchPresetSelection'](arg1);
}

export function SetBatchWorkflowState(arg1) {
  return window['go']['main']['App']['SetBatchWorkflowState'](arg1);
}

export function SetDeveloperMode(arg1) {
  return window['go']['main']['App']['SetDeveloperMode'](arg1);
}

export function SetGatewayURL(arg1) {
  return window['go']['main']['App']['SetGatewayURL'](arg1);
}

export function SetRegressionWatchProfiles(arg1) {
  return window['go']['main']['App']['SetRegressionWatchProfiles'](arg1);
}

export function SetRegressionWatchSettings(arg1) {
  return window['go']['main']['App']['SetRegressionWatchSettings'](arg1);
}

export function Smoke(arg1) {
  return window['go']['main']['App']['Smoke'](arg1);
}

export function StartBatchPresetEval(arg1) {
  return window['go']['main']['App']['StartBatchPresetEval'](arg1);
}

export function StartBatchPresetIngest(arg1) {
  return window['go']['main']['App']['StartBatchPresetIngest'](arg1);
}

export function StartBatchPresetIngestEval(arg1) {
  return window['go']['main']['App']['StartBatchPresetIngestEval'](arg1);
}

export function StartBatchPresetRuntimeStackPrepare(arg1) {
  return window['go']['main']['App']['StartBatchPresetRuntimeStackPrepare'](arg1);
}

export function StartBatchPresetSmoke(arg1) {
  return window['go']['main']['App']['StartBatchPresetSmoke'](arg1);
}

export function StartBatchPresetStackIngestEval(arg1) {
  return window['go']['main']['App']['StartBatchPresetStackIngestEval'](arg1);
}

export function StartBatchPresetValidate(arg1) {
  return window['go']['main']['App']['StartBatchPresetValidate'](arg1);
}

export function StartBatchPresetVerification(arg1) {
  return window['go']['main']['App']['StartBatchPresetVerification'](arg1);
}

export function StartBatchPresetWatch(arg1) {
  return window['go']['main']['App']['StartBatchPresetWatch'](arg1);
}

export function StartCode() {
  return window['go']['main']['App']['StartCode']();
}

export function StartCoreStack() {
  return window['go']['main']['App']['StartCoreStack']();
}

export function StartEmbedding() {
  return window['go']['main']['App']['StartEmbedding']();
}

export function StartFast() {
  return window['go']['main']['App']['StartFast']();
}

export function StartGateway() {
  return window['go']['main']['App']['StartGateway']();
}

export function StartQdrant() {
  return window['go']['main']['App']['StartQdrant']();
}

export function StartRecommendedStack() {
  return window['go']['main']['App']['StartRecommendedStack']();
}

export function StartWatch(arg1) {
  return window['go']['main']['App']['StartWatch'](arg1);
}

export function StartWork() {
  return window['go']['main']['App']['StartWork']();
}

export function StopCode() {
  return window['go']['main']['App']['StopCode']();
}

export function StopCoreStack() {
  return window['go']['main']['App']['StopCoreStack']();
}

export function StopEmbedding() {
  return window['go']['main']['App']['StopEmbedding']();
}

export function StopFast() {
  return window['go']['main']['App']['StopFast']();
}

export function StopGateway() {
  return window['go']['main']['App']['StopGateway']();
}

export function StopQdrant() {
  return window['go']['main']['App']['StopQdrant']();
}

export function StopRecommendedStack() {
  return window['go']['main']['App']['StopRecommendedStack']();
}

export function StopWatch() {
  return window['go']['main']['App']['StopWatch']();
}

export function StopWork() {
  return window['go']['main']['App']['StopWork']();
}

export function ValidateProjectPreset(arg1) {
  return window['go']['main']['App']['ValidateProjectPreset'](arg1);
}
