// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyLocalModel(arg1:main.ApplyLocalModelRequest):Promise<main.LocalModelCatalog>;

export function ApproveWebSearch(arg1:string):Promise<Record<string, any>>;

export function BrowseIndex(arg1:main.IndexBrowseRequest):Promise<Record<string, any>>;

export function CancelBatchWorkflow():Promise<main.BatchWorkflowState>;

export function Chat(arg1:main.ChatRequest):Promise<main.ChatResponse>;

export function ClearBatchPresetSelection():Promise<Array<string>>;

export function ClearBatchWorkflowState():Promise<main.BatchWorkflowState>;

export function ClearExecutionHistory():Promise<Array<main.ExecutionHistoryItem>>;

export function DeleteLocalConfigFile(arg1:main.LocalConfigNameRequest):Promise<Array<main.LocalConfigFile>>;

export function DeleteProjectPreset(arg1:main.LocalConfigNameRequest):Promise<Array<main.ProjectPreset>>;

export function DeleteSavedRequest(arg1:main.LocalConfigNameRequest):Promise<Array<main.SavedRequest>>;

export function Embeddings(arg1:main.EmbeddingRequest):Promise<Record<string, any>>;

export function Eval(arg1:main.EvalRequest):Promise<main.EvalResponse>;

export function ExportResult(arg1:main.ExportResultRequest):Promise<main.ExportResultResponse>;

export function GetBatchPresetSelection():Promise<Array<string>>;

export function GetBatchWorkflowState():Promise<main.BatchWorkflowState>;

export function GetExecutionHistory():Promise<Array<main.ExecutionHistoryItem>>;

export function GetGatewayURL():Promise<string>;

export function GetIndexSource(arg1:main.IndexSourceRequest):Promise<Record<string, any>>;

export function GetLocalConfigFiles():Promise<Array<main.LocalConfigFile>>;

export function GetLocalModelCatalog():Promise<main.LocalModelCatalog>;

export function GetProjectPresets():Promise<Array<main.ProjectPreset>>;

export function GetRegressionWatchProfiles():Promise<Record<string, main.RegressionWatchProfile>>;

export function GetRegressionWatchSettings():Promise<main.RegressionWatchSettings>;

export function GetRuntimeStatus():Promise<main.RuntimeStatus>;

export function GetSavedRequests():Promise<Array<main.SavedRequest>>;

export function Health():Promise<main.HealthResponse>;

export function ImportLocalModel(arg1:main.ImportLocalModelRequest):Promise<main.LocalModelCatalog>;

export function Ingest(arg1:main.IngestRequest):Promise<Record<string, any>>;

export function ListExportedResults():Promise<Array<main.ExportedFileItem>>;

export function LoadLocalConfigExample(arg1:main.LocalConfigNameRequest):Promise<main.LocalConfigFile>;

export function Models():Promise<main.ModelListResponse>;

export function OpenWebSource(arg1:string):Promise<void>;

export function PlanWebSearch(arg1:string):Promise<main.WebSearchPlanResponse>;

export function Query(arg1:main.QueryRequest):Promise<main.QueryResponse>;

export function ReadExportedResult(arg1:main.ExportedFileRequest):Promise<main.ExportedFileContent>;

export function RecordExecution(arg1:main.ExecutionHistoryItem):Promise<Array<main.ExecutionHistoryItem>>;

export function ReloadGatewayConfig():Promise<main.ReloadConfigResponse>;

export function RoutePlan(arg1:main.RoutePlanRequest):Promise<main.RoutePlanResponse>;

export function RunChatAction(arg1:main.ChatRequest):Promise<main.ChatResponse>;

export function RunEmbeddingAction(arg1:main.EmbeddingRequest):Promise<Record<string, any>>;

export function RunEvalAction(arg1:main.EvalRequest):Promise<main.EvalResponse>;

export function RunIndexBrowseAction(arg1:main.IndexBrowseRequest):Promise<Record<string, any>>;

export function RunIngestAction(arg1:main.IngestRequest):Promise<Record<string, any>>;

export function RunPresetEval(arg1:main.ProjectPreset):Promise<main.WorkflowRunResponse>;

export function RunPresetIngest(arg1:main.ProjectPreset):Promise<main.WorkflowRunResponse>;

export function RunPresetIngestEval(arg1:main.ProjectPreset):Promise<main.WorkflowRunResponse>;

export function RunPresetRecoveryAction(arg1:main.PresetRecoveryActionRequest):Promise<main.WorkflowRunResponse>;

export function RunPresetRuntimeStackPrepare(arg1:main.ProjectPreset):Promise<main.WorkflowRunResponse>;

export function RunPresetSmoke(arg1:main.ProjectPreset):Promise<main.WorkflowRunResponse>;

export function RunPresetStackIngestEval(arg1:main.ProjectPreset):Promise<main.WorkflowRunResponse>;

export function RunPresetValidate(arg1:main.ProjectPreset):Promise<main.WorkflowRunResponse>;

export function RunPresetVerification(arg1:main.ProjectPreset):Promise<main.WorkflowRunResponse>;

export function RunPresetWatch(arg1:main.ProjectPreset):Promise<main.WorkflowRunResponse>;

export function RunRagQueryAction(arg1:main.QueryRequest):Promise<main.QueryResponse>;

export function RunRagSearchAction(arg1:main.SearchRequest):Promise<main.SearchResponse>;

export function RunRuntimeConfigAction(arg1:main.RuntimeConfigActionRequest):Promise<main.WorkflowRunResponse>;

export function RunRuntimeServiceAction(arg1:main.RuntimeServiceActionRequest):Promise<main.WorkflowRunResponse>;

export function RunRuntimeSmoke(arg1:main.SmokeRequest):Promise<main.WorkflowRunResponse>;

export function RunRuntimeStackAction(arg1:main.RuntimeStackActionRequest):Promise<main.WorkflowRunResponse>;

export function SaveLocalConfigFile(arg1:main.SaveLocalConfigRequest):Promise<Array<main.LocalConfigFile>>;

export function SaveProjectPreset(arg1:main.ProjectPreset):Promise<Array<main.ProjectPreset>>;

export function SaveRequest(arg1:main.SavedRequest):Promise<Array<main.SavedRequest>>;

export function Search(arg1:main.SearchRequest):Promise<main.SearchResponse>;

export function SetBatchPresetSelection(arg1:Array<string>):Promise<Array<string>>;

export function SetBatchWorkflowState(arg1:main.BatchWorkflowState):Promise<main.BatchWorkflowState>;

export function SetDeveloperMode(arg1:boolean):Promise<boolean>;

export function SetGatewayURL(arg1:string):Promise<string>;

export function SetRegressionWatchProfiles(arg1:Record<string, main.RegressionWatchProfile>):Promise<Record<string, main.RegressionWatchProfile>>;

export function SetRegressionWatchSettings(arg1:main.RegressionWatchSettings):Promise<main.RegressionWatchSettings>;

export function Smoke(arg1:main.SmokeRequest):Promise<main.SmokeResponse>;

export function StartBatchPresetEval(arg1:main.BatchPresetWorkflowRequest):Promise<main.BatchWorkflowState>;

export function StartBatchPresetIngest(arg1:main.BatchPresetWorkflowRequest):Promise<main.BatchWorkflowState>;

export function StartBatchPresetIngestEval(arg1:main.BatchPresetWorkflowRequest):Promise<main.BatchWorkflowState>;

export function StartBatchPresetRuntimeStackPrepare(arg1:main.BatchPresetWorkflowRequest):Promise<main.BatchWorkflowState>;

export function StartBatchPresetSmoke(arg1:main.BatchPresetWorkflowRequest):Promise<main.BatchWorkflowState>;

export function StartBatchPresetStackIngestEval(arg1:main.BatchPresetWorkflowRequest):Promise<main.BatchWorkflowState>;

export function StartBatchPresetValidate(arg1:main.BatchPresetWorkflowRequest):Promise<main.BatchWorkflowState>;

export function StartBatchPresetVerification(arg1:main.BatchPresetWorkflowRequest):Promise<main.BatchWorkflowState>;

export function StartBatchPresetWatch(arg1:main.BatchPresetWorkflowRequest):Promise<main.BatchWorkflowState>;

export function StartCode():Promise<main.RuntimeStatus>;

export function StartCoreStack():Promise<main.StackActionResponse>;

export function StartEmbedding():Promise<main.RuntimeStatus>;

export function StartFast():Promise<main.RuntimeStatus>;

export function StartGateway():Promise<main.RuntimeStatus>;

export function StartQdrant():Promise<main.RuntimeStatus>;

export function StartRecommendedStack():Promise<main.StackActionResponse>;

export function StartWatch(arg1:main.WatchRequest):Promise<main.RuntimeStatus>;

export function StartWork():Promise<main.RuntimeStatus>;

export function StopCode():Promise<main.RuntimeStatus>;

export function StopCoreStack():Promise<main.StackActionResponse>;

export function StopEmbedding():Promise<main.RuntimeStatus>;

export function StopFast():Promise<main.RuntimeStatus>;

export function StopGateway():Promise<main.RuntimeStatus>;

export function StopQdrant():Promise<main.RuntimeStatus>;

export function StopRecommendedStack():Promise<main.StackActionResponse>;

export function StopWatch():Promise<main.RuntimeStatus>;

export function StopWork():Promise<main.RuntimeStatus>;

export function ValidateProjectPreset(arg1:main.ProjectPreset):Promise<main.PresetValidationResponse>;
